In [ ]:
import pandas as pd
import numpy as np

df1 = pd.read_csv('https://raw.githubusercontent.com/sagurah/TubesPBO/main/neo.csv')
df1.head(5)

id                 name  est_diameter_min  est_diameter_max  \
0  2162635  162635 (2000 SS164)          1.198271          2.679415   
1  2277475    277475 (2005 WK4)          0.265800          0.594347   
2  2512244   512244 (2015 YE18)          0.722030          1.614507   
3  3596030          (2012 BV13)          0.096506          0.215794   
4  3667127          (2014 GE35)          0.255009          0.570217   

   relative_velocity  miss_distance orbiting_body  sentry_object  \
0       13569.249224   5.483974e+07         Earth          False   
1       73588.726663   6.143813e+07         Earth          False   
2      114258.692129   4.979872e+07         Earth          False   
3       24764.303138   2.543497e+07         Earth          False   
4       42737.733765   4.627557e+07         Earth          False   

   absolute_magnitude  hazardous  
0               16.73      False  
1               20.00       True  
2               17.83      False  
3               22.20      False  
4               20.09       True

In [ ]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()

# # labelHazard = le.fit_transform(df1['hazardous'])
# labelSentry = le.fit_transform(df1['sentry_object'])
# # df1.drop('hazardous', axis=1, inplace=True)
# # df1.drop('sentry_object', axis=1, inplace=True)
# # df1.drop('orbiting_body', axis=1, inplace=True)  #menghapus orbiting_body karena semuanya Earth
# # df1.drop('name', axis=1, inplace=True)
# # df1.drop('id', axis=1, inplace=True)

# # df1['hazardous'] = labelHazard
# df1['sentry_object'] = labelSentry

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

X = df1.drop(['id','name','est_diameter_max','orbiting_body','sentry_object','hazardous'],axis=1)
y = df1.hazardous.astype('int')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

scaler = MinMaxScaler()
scaler.fit(X_train)

X_train_mmscaled = scaler.transform(X_train)
X_test_mmscaled = scaler.transform(X_test)

# print("Score train before scaled: ".format(scaler.score(X_train)))
# print("Score test before scaled: ".format(scaler.score(X_test)))
# print("Score train after scaled: ".format(scaler.score(X_train_mmscaler)))
# print("Score test after scaled: ".format(scaler.score(X_test_mmscaler)))

print("X_train_mmscaled : ")
print(X_train_mmscaled)
print("\n\nX_test_mmscaled : ")
print(X_test_mmscaled)

print("\n\n\nper-feature minimum before scaling:\n {}".format(X_train.min(axis=0)))
print("per-feature maximum before scaling:\n {}".format(X_train.max(axis=0)))
print("per-feature minimum after scaling:\n {}".format(
    X_train_mmscaled.min(axis=0)))
print("per-feature maximum after scaling:\n {}".format(
    X_train_mmscaled.max(axis=0)))

X_train_mmscaled : 
[[1.18562181e-05 1.16894717e-01 5.32035392e-01 9.49937422e-01]
 [7.53073131e-04 2.09737939e-01 2.40276345e-01 6.49561952e-01]
 [6.85396900e-04 1.16244798e-01 1.80390884e-01 6.57905715e-01]
 ...
 [5.94882172e-04 2.30283695e-01 7.93964618e-01 6.70421360e-01]
 [2.11210357e-03 2.08368077e-01 5.08225818e-01 5.57363371e-01]
 [1.59089741e-03 1.58772594e-01 4.59485892e-01 5.82811848e-01]]


X_test_mmscaled : 
[[3.19673340e-04 2.63673865e-01 7.17397385e-01 7.24655820e-01]
 [4.83689332e-03 2.20398289e-01 2.55675840e-01 4.82686692e-01]
 [1.44627037e-04 1.05568055e-01 7.48568264e-03 7.91405924e-01]
 ...
 [3.66527922e-03 2.50071098e-01 6.94863433e-01 5.07717981e-01]
 [1.30487469e-04 1.58968936e-01 6.69574558e-03 7.99749687e-01]
 [4.92097938e-04 1.50380514e-01 4.31769553e-02 6.87108886e-01]]



per-feature minimum before scaling:
 est_diameter_min         0.000609
relative_velocity      271.446828
miss_distance         6745.532516
absolute_magnitude       9.230000
dtype: float64


In [ ]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

X_train_stdscaled = std_scaler.fit(X_train).transform(X_train)
X_test_stdscaled = std_scaler.transform(X_test)

print('X_train Standard Scaler: ')
print(X_train_stdscaled)
print('\n\nX_test Standard Scaler: ')
print(X_test_stdscaled)

print("\n\n\nper-feature minimum before scaling:\n {}".format(X_train.min(axis=0)))

print("per-feature maximum before scaling:\n {}".format(X_train.max(axis=0)))
print("per-feature minimum after scaling:\n {}".format(
    X_train_stdscaled.min(axis=0)))
print("per-feature maximum after scaling:\n {}".format(
    X_train_stdscaled.max(axis=0)))

X_train Standard Scaler: 
[[-0.41855692 -0.79657683  0.11822139  2.92919472]
 [-0.32544362  0.07190351 -0.85832669  0.44176864]
 [-0.33394526 -0.80265634 -1.0587696   0.51086381]
 ...
 [-0.34531592  0.26409401  0.99492594  0.61450656]
 [-0.15471923  0.05908946  0.03852826 -0.32173298]
 [-0.2201943  -0.40483996 -0.12460938 -0.11099271]]


X_test Standard Scaler: 
[[-0.37988826  0.57643459  0.7386474   1.06362516]
 [ 0.18757484  0.17162328 -0.80678297 -0.94013474]
 [-0.40187796 -0.90252945 -1.63750142  1.61638651]
 ...
 [ 0.0403941   0.44919067  0.6632239  -0.73284923]
 [-0.4036542  -0.40300332 -1.64014542  1.68548168]
 [-0.3582279  -0.48334173 -1.51803899  0.7526969 ]]



per-feature minimum before scaling:
 est_diameter_min         0.000609
relative_velocity      271.446828
miss_distance         6745.532516
absolute_magnitude       9.230000
dtype: float64
per-feature maximum before scaling:
 est_diameter_min      3.789265e+01
relative_velocity     2.369901e+05
miss_distance         7.4

In [ ]:
from sklearn.svm import SVC
from sklearn.feature_selection import SelectKBest

feat_select = 4
selector = SelectKBest(k=feat_select)
accuracy = selector.fit(X_train_mmscaled, y_train)
X_train_mmsk = selector.fit_transform(X_train_mmscaled, y_train)
print(X_train_mmscaled.shape)
print(y_train.shape)
X_test_mmsk = selector.fit_transform(X_test_mmscaled, y_test)

features = [f for f, s in zip(X.columns, selector.get_support()) if s]

best_score = 0
for gamma in[0.001, 0.01, 0.1, 1]:
    for C in [0.001, 0.01, 0.1, 1]:
        svm = SVC(gamma=gamma, C=C)
        svm.fit(X_train_mmsk, y_train)
        score = svm.score(X_test_mmsk, y_test)
        # if we got a better score, store the score and parameter
        print("a")
        if score > best_score:
            best_score = score
            best_parameters = {'C': C, 'gamma': gamma}

# print("Best Features: {}".format(features))
# print("Best score: {:.2f}".format(best_score))
# print("Best parameters: {}".format(best_parameters))
print("Accuracy train set: {:.2f}".format(svc.score(X_train_mmsk, y_train)))
print("Accuracy test set: {:.2f}".format(svc.score(X_test_mmsk, y_test)))

(63585, 4)
(63585,)
a
a
a
a
a


In [ ]:
from sklearn.feature_selection import SelectPercentile

SP = SelectPercentile(percentile=30)
SP.fit(X_train_mmscaled, y_train)
X_train_selected = SP.transform(X_train_mmscaled)

print('X_train.shape: {}'.format(X_train.shape))
print('X_train_selected.shape: {}'.format(X_train_selected.shape))